name: "Haas+Sohn Pellet Stove"
description: "Add a Haas+Sohn Pellet Stove to your Homeassistant - unofficial Version"
version: "1.0.1e"
slug: "hsp_mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  hsp_stove_ip: ""
  hsp_stove_pin: 0000
  hsp_poll_interval: 15
  mqtt_ip: ""
  mqtt_port: 1883
  mqtt_use_auth: true
  mqtt_user: ""
  mqtt_password: ""
schema:
  hsp_stove_ip: str
  hsp_stove_pin: int
  hsp_poll_interval: int
  mqtt_ip: str
  mqtt_port: int
  mqtt_use_auth: bool
  mqtt_user: str
  mqtt_password: str
